services:
  mi_dinero_api:
    platform: linux/arm64/v8
    image: node:22-alpine
    container_name: mi_dinero_api
    working_dir: /app
    volumes:
      - .:/app:rw
      - root_mi_dinero_data:/app/data
    env_file: .env
    expose:
      - "${PORT}"
    ports:
      - "${PORT}:${PORT}"
    command: sh -c "npm install && npm run dev"
    networks:
      - local_network
    restart: always

networks:
  local_network:
    external: true
    name: local_network

volumes:
  root_mi_dinero_data: